FROM ubuntu:18.04

ENV DEBIAN_FRONTEND=noninteractive
ENV TZ=UTC

RUN apt-get update      \
 && apt-get install -y  \
      openssh-server    \
      sudo              \
      awscli            \
      curl              \
      git               \
      jq                \
      vim

RUN apt-get update      \
 && apt-get install -y  \
 zlib1g                 \
 libssl1.1              \
 libcurl4

RUN mkdir /var/run/sshd

EXPOSE 22
